### ISSUE TITLE
Incorrect use of SSL_write leads to OpenSSL.SSL.Error exception

### ISSUE THREAD

**Issue by horazont** [horazont/aioopenssl#4]
See horazont/aioxmpp#116. @jomag reported:
```
[3286.014] ERR:  [asyncio] Fatal write error on STARTTLS transport
protocol: <aioxmpp.protocol.XMLStream object at 0xb41d0ad0>
transport: <aioopenssl.STARTTLSTransport object at 0xb41d0c10>Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/aioopenssl/__init__.py", line 478, in _write_ready
    nsent = self._sock.send(bytes(self._buffer))
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1254, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1172, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.5/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
```

[Reseraching the error condition](https://stackoverflow.com/a/3003410/1248008), it appears that OpenSSL by default does not allow you to change the buffer pointer or size between SSL_write calls which returned with a "NEED_READ" or "NEED_WRITE" condition.

**Comment by horazont** [comment]
A fix was implemented in 042fbdc.

Unfortunately, I have no idea how to provoke this specific condition to ensure that it actually works.

**Comment by jomag** [comment]
I've had this problem occur frequently at two (physical) locations. At the first location these two original issues were reported. I installed a workaround in aioxmpp and later the aioopenssl fix. After the workaround was installed there has been no more errors of this kind.

On the second location I installed aioopenssl and aioxmpp from master and there has been no more errors there either.

Given that, I think it's safe to regard this issue as resolved.

**Comment by horazont** [comment]
Nice, thanks for reporting the resolution!

**Comment by delfick** [comment]
I was still getting this error. I updated to 0.5.1 and same.

```
14:56:15 ERROR   asyncio         Fatal read error on STARTTLS transport
protocol: <photons_transport.transports.tcp.TCP.make_socket_protocol.<locals>.Protocol object at 0x10b093dc0>
transport: <aioopenssl.STARTTLSTransport object at 0x10b0f0980>
Traceback (most recent call last):
  File "/Users/stephenmoore/Projects/photons/scripts/.lifx/lib/python3.8/site-packages/aioopenssl/__init__.py", line 459, in _read_ready
    data = self._sock.recv(self.MAX_SIZE)
  File "/Users/stephenmoore/Projects/photons/scripts/.lifx/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1809, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/Users/stephenmoore/Projects/photons/scripts/.lifx/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1664, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```
